#ifndef ENGINE_LIST_DEFINITIONS_H
#define ENGINE_LIST_DEFINITIONS_H

DECLARE_LIST(vector2)
DECLARE_LIST(vector3)
DECLARE_LIST(GLuint)

DEFINE_LIST(vector2)
DEFINE_LIST(vector3)
DEFINE_LIST(GLuint)

#endif // ENGINE_LIST_DEFINITIONS_H
